apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
commonLabels:
  environment: production
configMapGenerator:
- name: my-application-properties
  behavior: merge
  envs:
  - application.properties
secretGenerator:
- name: mongo-secret
  behavior: replace
  envs:
  - secrets.txt
  type: Opaque
images:
  - name: mongo
    newTag: jammy
resources:
- ../../base
patches:
 - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ingress-service
   path: ingress-patch.yaml